---
name: Linter
on:
# Will run this runner when an action is made through Github
  workflow_dispatch: 
jobs:
  super-lint:
    name: Lint incoming code
    runs-on: self-hosted            # Runs on machine labeled self-hosted
    steps:
      - name: Checkout code
        uses: action/checkout@v4
      - name: Runs super linter
        uses: super-linter/super-linter@v7.1.0      # This is the latest version for super linter
        env:
          DEFUALT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
